apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client-server
  labels:
    app: go-client-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-client-server
  template:
    metadata:
      labels:
        app: go-client-server
    spec:
      containers:
      - name: go-client-server
        image: thomas3212/go-client-server
        imagePullPolicy: Never
        ports:
        - containerPort: 3000